version: '3.8'

services:
  app:
    build: .
    container_name: my-golang-app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: learn_tuxedo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
