version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: 1.24.1
    container_name: my-golang-app
    ports:
      - "8000:8000"  # Changed to PORT 8000
    volumes:
      - .:/app
      - /app/go/pkg/mod
    environment:
      - GOTOOLCHAIN=go1.24.1
      - PORT=8000
      - DATABASE=root:admin@tcp(db:3306)/learn_tuxedo?charset=utf8mb4&parseTime=True&loc=Local  # Modified connection string
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Changed password to 'admin'
      MYSQL_DATABASE: learn_tuxedo
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  db_data:
